mainSections = ['posts', 'projects']

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true


# you can set multi row of footers like these
[[footer_rows]]
[[footer_rows.items]]
name = "Creative Commons Attribution 4.0 International"
url = "https://creativecommons.org/licenses/by/4.0/"
pre = "Copyright © 2024 Jeremy Tsang"

[[footer_rows]]
[[footer_rows.items]]
name = "Hugo"
url = "https://gohugo.io"
pre = "Powered by <a href=\"https://gohugo.io\">Hugo</a> and <a href=\"https://ox-hugo.scripter.co/\">ox-hugo</a>."
[[footer_rows.items]]
name = "theme flat"
url = "https://github.com/jeremytsang1/hugo-theme-flat"
pre = "Theme <a href=\"https://github.com/jeremytsang1/hugo-theme-flat\">hugo-theme-flat</a>"
