#!/usr/bin/env bash

# Access deploy site at `https://web.engr.oregonstate.edu/~tsangj/`
# Assumes sass is globally accessible on flip (use `npm install -g sass`) for
# styling theme.
main() {
    local -r HOST='flip1'
    local -r DIR='/nfs/stak/users/tsangj/public_html'


    hugo && rsync -avz --delete public/ "${HOST}:${DIR}"
}

main "$@"
