title = "JeTs"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 4
# baseURL = ""

[module]
  [[module.imports]]
    path = "github.com/jeremytsang1/hugo-theme-flat"

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
# hl_Lines = ''
# lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[params]
mainSections = ['posts']

[[menus.main]]
name = "Posts"
url = "/posts/"
weight = 30

