#+hugo_base_dir: ../
#+STARTUP: logdone
* Posts
** DONE OSU CS 467: Blog Post Week 1                              :@CS__467:
CLOSED: [2024-01-11 Thu 17:54]
:PROPERTIES:
:EXPORT_FILE_NAME: cs-467-post-week-1
:END:
Hi, my name is Jeremy Tsang and I am excited to be graduating this quarter!
This course, CS 467, will be my final class and I hope I will be able to make
something interesting. My background before OSU was in chemistry. In my first
undergrad career I was mostly focused on computational/theoretical chemistry
and afterwards attempted to pursue a graduate degree in it. To this day I think
it is the subject I had the most fun studying, but unfortunately jobs in the
field are far and few between. As a result I had to shift industries to
something more practical and worked as a teacher and tutor for a little bit and
then did some work in an agricultural chemistry lab. However, my time studying
studying computational chemistry exposed me to programming. While working I
always wondered if I would have more fun coding than doing routine lab work.

My suspicisions were confirmed when I began my coursework at OSU. I did enjoy
most of the courses I have taken, especially the upper division ones like OS,
parallel programming, and mobile development. In addition to the material being
interesting, the instructors for those courses were great which added quite a
bit to the learning experience. They were time consuming though and I did have
to switch jobs once again as I found myself wasting a lot of time commuting at
my previous job. However, some things in life happened and I had to take a
break from school back in late 2022 while having to settle for work in retail
temporarily. It is good to be back though!

With regards to favorite technologies, I would have to say the one I spend most
of my free time on is GNU Emacs. I was introduced to it during my chemistry
days and there is just something addicting about being able to configure it
exactly to my liking as well as doing everything from a single
program/context. Although my first experience with it was of course just a text
editor, over the years configuring it has become more like a hobby. In addition
to development I also use it for browsing the internet, reading PDFs, taking
notes, scheduling tasks in my life with its agenda, and more. Due to its nature
as a Lisp interpreter it ascends from being an editor to being platform for
building text based apps. I am not the best when it comes to Emacs Lisp but I
have gotten to the point where I can comfortably tinker with most things after
reading the docs. Since nearly everything can be customized one way or another
via Emacs Lisp this gives a large amount of control over packages (similar to
VS Code extensions) that one uses. Any text related experience can be made to
fit like a glove should I choose to invest the time to research it. Sometimes
this can manifest as simple as rebinding a keyboard shortcut. Other times it
can be more complex like writing a helper function to generate a LaTeX snippet
for a polynomial of arbitrary degree. It does come at a cost however as it is
easy to get carried away [[https://en.wiktionary.org/wiki/yak_shaving][yak shaving]].

Other than tinkering with Emacs, I like to spend time my free time
weightlifting. I previously competed powerlifting but started [[https://en.wikipedia.org/wiki/Olympic_weightlifting][weightlifting]]
because I always thought snatching and clean and jerking looked
challenging. Other hobbies I used to indulge in more frequently include
playing/engraving piano music, playing old PC games (Dark Souls 2 and Heroes of
Might and Magic 3 are two favorites), and reading (mostly fantasy but sometimes
non-fiction). Time always seems too short these days to get to everything
though!

* DONE About
CLOSED: [2024-01-11 Thu 02:17]
:PROPERTIES:
:EXPORT_FILE_NAME: about
:EXPORT_HUGO_SECTION: /
:END:
Hello, my name is JeTs. Sometimes I go by Jeremy Tsang.
** Interests
- Computer Science
- Math
- GNU Emacs (Since 2012)
- Weightlifting (Since 2023)
- Powerlifting (Since 2012)
- Piano (Since 1996)
** Educational Background
- B.S. in Chemistry (2011)
- B.A. in Pure Mathematics (2011)
- B.S. in Computer Science (W.I.P.)
* Spelling
LocalWords: LocalWords
